
let allflights = [
  {
    id: 0,
    price: 4505,
    duration: '1h 17m',
    originCity: 'Pune',
    originCityCode: 'PNQ',
    stop: 'Non-stop',
    seatsLeft: '5',
    destCity: 'Delhi',
    destCityCode: 'DEL',
    deptDateTime: '10.00 am',
    retDateTime: '12.00 pm',
    name: 'Go-Air',
    number: 'G8-329'
  },
  {
    id: 1,
    price: 9508,
    duration: '2h 13m',
    originCity: 'Delhi',
    originCityCode: 'DEL',
    stop: 'Non-stop',
    seatsLeft: '2',
    destCity: 'Pune',
    destCityCode: 'PNQ',
    deptDateTime: '08.00 pm',
    retDateTime: '11.00 pm',
    name: 'IndiGo',
    number: '6E-171'
  },
  {
    id: 2,
    price: 4897,
    duration: '1h 24m',
    originCity: 'Hyderabad',
    originCityCode: 'HYD',
    stop: 'Non-stop',
    seatsLeft: '6',
    destCity: 'Bengaluru',
    destCityCode: 'BLR',
    deptDateTime: '07.00 am',
    retDateTime: '08.00 am',
    name: 'Jet-Airways',
    number: '9W-340'
  },
  {
    id: 3,
    price: 3580,
    duration: '2h 56m',
    originCity: 'Bengaluru',
    originCityCode: 'BLR',
    stop: '1 stop',
    seatsLeft: '10',
    destCity: 'Hyderabad',
    destCityCode: 'HYD',
    deptDateTime: '05.00 pm',
    retDateTime: '06.00 pm',
    name: 'Vistara',
    number: 'UK-983'
  },
  {
    id: 4,
    price: 5068,
    duration: '2h 33m',
    originCity: 'Pune',
    originCityCode: 'PNQ',
    seatsLeft: '13',
    destCity: 'Delhi',
    destCityCode: 'DEL',
    deptDateTime: '11.00 am',
    retDateTime: '01.00 pm',
    name: 'Spicejet',
    number: 'SG-161',
  },
  {
    id: 5,
    price: 5788,
    duration: '2h 35m',
    originCity: 'Delhi',
    originCityCode: 'DEL',
    stop: 'Non-stop',
    seatsLeft: '2',
    destCity: 'Pune',
    destCityCode: 'PNQ',
    deptDateTime: '10.00 pm',
    retDateTime: '12.00 am',
    name: 'Jet-Airways',
    number: '9W-323'
  },
  {
    id: 6,
    price: 4904,
    duration: '1h 10m',
    originCity: 'Hyderabad',
    originCityCode: 'HYD',
    seatsLeft: '4',
    stop: '1 stop',
    destCity: 'Bengaluru',
    destCityCode: 'BLR',
    deptDateTime: '09.00 am',
    retDateTime: '10.00 am',
    name: 'Vistara',
    number: 'UK-995',
  },
  {
    id: 7,
    price: 5503,
    duration: '1h 48m',
    originCity: 'Bengaluru',
    originCityCode: 'BLR',
    stop: '1 stop',
    seatsLeft: '4',
    destCity: 'Hyderabad',
    destCityCode: 'HYD',
    deptDateTime: '09.00 pm',
    retDateTime: '10.00 pm',
    name: 'Air India',
    number: 'AI-678',
  },
  {
    id: 8,
    price: 6650,
    duration: '2h 20m',
    originCity: 'Bengaluru',
    originCityCode: 'BLR',
    stop: 'Non-stop',
    seatsLeft: '8',
    destCity: 'Delhi',
    destCityCode: 'DEL',
    deptDateTime: '05.00 am',
    retDateTime: '07.00 pm',
    name: 'IndiGo',
    number: '6E-904'
  },
  {
    id: 9,
    price: 6890,
    duration: '2h 40m',
    originCity: 'Delhi',
    originCityCode: 'DEL',
    stop: '1 stop',
    seatsLeft: '3',
    destCity: 'Bengaluru',
    destCityCode: 'BLR',
    deptDateTime: '08.30 pm',
    retDateTime: '10.30 pm',
    name: 'Go Air',
    number: 'G8-429'
  },
];

export {allflights};
